[12:21:20] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:33: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:33: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:33: ready to load the pre-computed wass distances
2022/03/31 12:21:33: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:33: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:33: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:33: gridsearch and crossvalidation done
[12:21:35] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:36: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:36: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:36: ready to load the pre-computed wass distances
2022/03/31 12:21:36: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:36: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:36: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:36: gridsearch and crossvalidation done
[12:21:37] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:38: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:38: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:38: ready to load the pre-computed wass distances
2022/03/31 12:21:38: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:38: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:38: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:38: gridsearch and crossvalidation done
[12:21:40] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:41: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:41: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:41: ready to load the pre-computed wass distances
2022/03/31 12:21:41: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:41: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:41: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:41: gridsearch and crossvalidation done
[12:21:43] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:44: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:44: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:44: ready to load the pre-computed wass distances
2022/03/31 12:21:44: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:44: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:44: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:44: gridsearch and crossvalidation done
[12:21:45] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:46: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:46: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:46: ready to load the pre-computed wass distances
2022/03/31 12:21:46: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:46: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:46: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:46: gridsearch and crossvalidation done
[12:21:48] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:49: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:49: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:49: ready to load the pre-computed wass distances
2022/03/31 12:21:49: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:49: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:49: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:49: gridsearch and crossvalidation done
[12:21:51] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:52: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:52: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:52: ready to load the pre-computed wass distances
2022/03/31 12:21:52: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:52: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:52: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:52: gridsearch and crossvalidation done
[12:21:53] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:54: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:54: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:54: ready to load the pre-computed wass distances
2022/03/31 12:21:54: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:54: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:54: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:54: gridsearch and crossvalidation done
[12:21:56] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:57: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:57: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:57: ready to load the pre-computed wass distances
2022/03/31 12:21:57: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:57: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:57: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:57: gridsearch and crossvalidation done
[12:21:58] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:21:59: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:59: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:21:59: ready to load the pre-computed wass distances
2022/03/31 12:21:59: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:21:59: Wasserstein distances computation done. Saved to file.
2022/03/31 12:21:59: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:21:59: gridsearch and crossvalidation done
[12:22:01] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:02: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:02: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:02: ready to load the pre-computed wass distances
2022/03/31 12:22:02: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:02: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:02: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:02: gridsearch and crossvalidation done
[12:22:04] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:05: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:05: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:05: ready to load the pre-computed wass distances
2022/03/31 12:22:05: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:05: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:05: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:05: gridsearch and crossvalidation done
[12:22:06] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:07: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:07: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:07: ready to load the pre-computed wass distances
2022/03/31 12:22:07: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:07: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:07: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:07: gridsearch and crossvalidation done
[12:22:09] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:10: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:10: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:10: ready to load the pre-computed wass distances
2022/03/31 12:22:10: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:10: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:10: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:10: gridsearch and crossvalidation done
[12:22:12] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:13: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:13: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:13: ready to load the pre-computed wass distances
2022/03/31 12:22:13: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:13: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:13: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:13: gridsearch and crossvalidation done
[12:22:14] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:15: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:15: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:15: ready to load the pre-computed wass distances
2022/03/31 12:22:15: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:15: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:15: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:15: gridsearch and crossvalidation done
[12:22:17] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:18: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:18: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:18: ready to load the pre-computed wass distances
2022/03/31 12:22:18: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:18: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:18: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:18: gridsearch and crossvalidation done
[12:22:20] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:21: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:21: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:21: ready to load the pre-computed wass distances
2022/03/31 12:22:21: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:21: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:21: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:21: gridsearch and crossvalidation done
[12:22:22] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:23: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:23: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:23: ready to load the pre-computed wass distances
2022/03/31 12:22:23: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:23: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:23: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:23: gridsearch and crossvalidation done
[12:22:25] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 12:22:26: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:26: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 12:22:26: ready to load the pre-computed wass distances
2022/03/31 12:22:26: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 12:22:26: Wasserstein distances computation done. Saved to file.
2022/03/31 12:22:26: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 12:22:26: gridsearch and crossvalidation done
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'exp/fig1:w_versue_hl/PTC_MR/WKS/results_PTC_MR_WKS_0.00_2022-03-31 12:19_crossvalidation.csv' that are
removed from your working tree are ignored with this version of Git.

* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.

Run 'git status' to check the paths you removed from your working tree.

