[13:15:45] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:15:48: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:48: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:48: ready to load the pre-computed wass distances
2022/03/31 01:15:48: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:15:48: Wasserstein distances computation done. Saved to file.
2022/03/31 01:15:48: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:15:48: gridsearch and crossvalidation done
[13:15:50] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:15:51: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:51: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:51: ready to load the pre-computed wass distances
2022/03/31 01:15:51: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:15:51: Wasserstein distances computation done. Saved to file.
2022/03/31 01:15:51: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:15:51: gridsearch and crossvalidation done
[13:15:52] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:15:53: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:53: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:53: ready to load the pre-computed wass distances
2022/03/31 01:15:53: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:15:53: Wasserstein distances computation done. Saved to file.
2022/03/31 01:15:53: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:15:53: gridsearch and crossvalidation done
[13:15:55] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:15:56: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:56: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:56: ready to load the pre-computed wass distances
2022/03/31 01:15:56: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:15:56: Wasserstein distances computation done. Saved to file.
2022/03/31 01:15:56: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:15:56: gridsearch and crossvalidation done
[13:15:58] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:15:59: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:59: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:15:59: ready to load the pre-computed wass distances
2022/03/31 01:15:59: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:15:59: Wasserstein distances computation done. Saved to file.
2022/03/31 01:15:59: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:15:59: gridsearch and crossvalidation done
[13:16:00] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:01: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:01: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:01: ready to load the pre-computed wass distances
2022/03/31 01:16:01: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:01: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:01: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:01: gridsearch and crossvalidation done
[13:16:03] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:04: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:04: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:04: ready to load the pre-computed wass distances
2022/03/31 01:16:04: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:04: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:04: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:04: gridsearch and crossvalidation done
[13:16:05] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:06: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:06: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:06: ready to load the pre-computed wass distances
2022/03/31 01:16:06: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:06: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:06: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:06: gridsearch and crossvalidation done
[13:16:08] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:09: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:09: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:09: ready to load the pre-computed wass distances
2022/03/31 01:16:09: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:09: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:09: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:09: gridsearch and crossvalidation done
[13:16:11] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:11: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:11: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:11: ready to load the pre-computed wass distances
2022/03/31 01:16:11: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:11: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:11: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:12: gridsearch and crossvalidation done
[13:16:13] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:14: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:14: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:14: ready to load the pre-computed wass distances
2022/03/31 01:16:14: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:14: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:14: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:14: gridsearch and crossvalidation done
[13:16:16] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:17: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:17: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:17: ready to load the pre-computed wass distances
2022/03/31 01:16:17: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:17: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:17: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:17: gridsearch and crossvalidation done
[13:16:18] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:19: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:19: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:19: ready to load the pre-computed wass distances
2022/03/31 01:16:19: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:19: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:19: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:19: gridsearch and crossvalidation done
[13:16:21] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:22: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:22: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:22: ready to load the pre-computed wass distances
2022/03/31 01:16:22: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:22: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:22: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:22: gridsearch and crossvalidation done
[13:16:23] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:24: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:24: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:24: ready to load the pre-computed wass distances
2022/03/31 01:16:24: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:24: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:24: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:24: gridsearch and crossvalidation done
[13:16:26] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:27: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:27: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:27: ready to load the pre-computed wass distances
2022/03/31 01:16:27: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:27: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:27: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:27: gridsearch and crossvalidation done
[13:16:28] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:29: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:29: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:29: ready to load the pre-computed wass distances
2022/03/31 01:16:29: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:29: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:29: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:29: gridsearch and crossvalidation done
[13:16:31] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:32: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:32: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:32: ready to load the pre-computed wass distances
2022/03/31 01:16:32: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:32: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:32: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:32: gridsearch and crossvalidation done
[13:16:33] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:34: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:34: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:34: ready to load the pre-computed wass distances
2022/03/31 01:16:34: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:34: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:34: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:34: gridsearch and crossvalidation done
[13:16:36] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:37: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:37: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:37: ready to load the pre-computed wass distances
2022/03/31 01:16:37: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:37: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:37: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:37: gridsearch and crossvalidation done
[13:16:39] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 01:16:40: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:40: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 01:16:40: ready to load the pre-computed wass distances
2022/03/31 01:16:40: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 01:16:40: Wasserstein distances computation done. Saved to file.
2022/03/31 01:16:40: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 01:16:40: gridsearch and crossvalidation done
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'exp/fig1:w_versue_hl/MUTAG/WKS/results_MUTAG_WKS_0.00_2022-03-31 13:11_crossvalidation.csv' that are
removed from your working tree are ignored with this version of Git.

* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.

Run 'git status' to check the paths you removed from your working tree.

